name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        go: ["1.20"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - run: go test ./...
      # benchmemを付けることで一処理あたりのメモリアロケーション数が得られます。
      - run: |
          cd ./cmd/aozora-collector
          go test -bench ./... -benchmem
